on:
  push:
    branches:
      - main

jobs:
  tests_e2e_chromium:
    name: Run end-to-end tests on chromium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies for the project
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests Chrome Only
        run: TESTS_RUNNING_IN_ENVIROMENTS=chromium npx playwright test --project=e2e-chromium   
